python3 ../../../main_pretrain.py \
    --dataset cifar100 \
    --encoder resnet18 \
    --data_dir ../../../../../../neurips-2021/ssl_aaai/bash_files/pretrain/cifar/datasets/ \
    --max_epochs 1000 \
    --gpus 5 \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.5 \
    --classifier_lr 0.1 \
    --weight_decay 1e-5 \
    --batch_size 256 \
    --num_workers 4 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.4 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --crop_size 32 \
    --num_crops_per_aug 1 1 \
    --zero_init_residual \
    --name nnsiam \
    --project solo-learn-cifar100-1021 \
    --entity kaistssl \
    --wandb \
    --save_checkpoint \
    --method nnsiam \
    --proj_hidden_dim 2048 \
    --pred_hidden_dim 4096 \
    --proj_output_dim 2048 \
    --checkpoint_frequency 100 \
